### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by CyberShadow** [archlinux/archlinux-docker#11]
For CI, dependencies need to be strictly versioned, so that a new version of dependencies does not unexpectedly break the build. Instead, dependencies' versions are bumped regularly (then, any breakages due to new versions can caught in the PR and addressed before landing in master).

Thus, any thoughts on tags, like the [base/archlinux](https://hub.docker.com/r/base/archlinux/tags) images?

Using the Arch Linux Archive + a forced downgrade might work as a workaround for now, but most likely not forever (upgrades/downgrades across large spans of time seem to require manual intervention).

**Comment by poidl** [comment]
I'm interested in this too. I'm aware that from a security perspective, it may be viewed as bad practice for a distribution provider to facilitate downgrading to old packages.

On the other hand, there are scenarios where it makes sense. E.g. containers are great to make numerical experiments reproducible. In this case the container's purpose is to build an artifact which is just numerical data, as opposed to the artifact being some application providing a security-sensitive service (perhaps even a public facing one). The way I see it, security is irrelevant in this case.

If I understand correctly, there are even distributions that provide this, which are specifically targeted for production use + have sort of rolling release model, e.g. Clearlinux. One of their goals is to make downgrading as simple as typing one command.

**Comment by poidl** [comment]
Also, instead of downgrading from within the running container, it might be easier to build the image from scratch with the old packages:

https://bbs.archlinux.org/viewtopic.php?pid=1802518#p1802518

I wrote that, let me know if it makes no sense.

Thanks for the reference, I din't know about that repository. That looks interesting!

**Comment by dradetsky** [comment]
I would like this as well. FWIW, I think even just adding a datestamp for every release would be helpful, even if it didn't facilitate everything described above.

**Comment by CyberShadow** [comment]
FWIW, building a Docker image from the Arch bootstrap installation tarballs is pretty easy. Here is how I do it in aconfmgr:

https://github.com/CyberShadow/aconfmgr/blob/8e34efd48aec5542539b3deb21db24aa5ed62f6f/test/GNUmakefile#L146-L173
https://github.com/CyberShadow/aconfmgr/blob/8e34efd48aec5542539b3deb21db24aa5ed62f6f/test/docker/Dockerfile.arch

**Comment by M3t0r** [comment]
You can use this snippet to get the date of the newest installed package:

```
docker run --rm archlinux/base pacman -Qi 2>/dev/null \
    | awk -F ' : ' '/Build Date/ {print $2}' \
    | sort -rsnk2 \
    | sort -rsMk3 \
    | sort -rsnk4 \
    | awk '{print $4 "-" $3 "-" $2}' \
    | head -n1
```

**Comment by SantiagoTorres** [comment]
Releases are tagged now on the [official images](https://hub.docker.com/_/archlinux)
