### ISSUE TITLE
Adding ARM64 support in Archlinux docker image

### ISSUE THREAD

**Issue by odidev** [archlinux/archlinux-docker#29]
Hi, 

Archlinux dockerimage presented on docker hub is not supporting arm64.
And to build the dockerimage from Makefile, base archlinux image is required which is not available for ARM64.
We have created a base archlinux docker image for arm64 and tested it locally. 
Can you suggest further actions to merge our arm64 changes in the docker hub for archlinux?

**Comment by shibumi** [comment]
Actually Arch Linux doesn't support any other architecture than AMD64.
If you would like to have an ARM64 docker image you need to ask the Arch  Linux ARM project: https://archlinuxarm.org/

These projects are two different things. Sorry.
