### ISSUE TITLE
Make usable with makepkg -s

### ISSUE THREAD

**Issue by mikkeloscar** [archlinux/archlinux-docker#3]
Hello

I'm trying to use this image as a base image for building packages with `makepkg`.

It's a bit tricky though because of [this hook](https://github.com/pierres/archlinux-docker/blob/master/rootfs/usr/share/libalpm/hooks/package-cleanup.hook) which cleans up the repo DBs causing makepkg to fail when installing dependencies through pacman:

```
$ makepkg --install --syncdeps --noconfirm
[info] Building package mimeo
==> Making package: mimeo 2017.6.6-1 (Wed Jun  7 20:28:16 UTC 2017)
==> Checking runtime dependencies...
warning: database file for 'maze' does not exist
warning: database file for 'core' does not exist
warning: database file for 'extra' does not exist
warning: database file for 'community' does not exist
warning: database file for 'multilib' does not exist
==> Installing missing dependencies...
warning: database file for 'maze' does not exist
warning: database file for 'core' does not exist
warning: database file for 'extra' does not exist
warning: database file for 'community' does not exist
warning: database file for 'multilib' does not exist
error: target not found: python-xdg
error: target not found: python3
```

I understand cleaning the DBs reduces the image size, but maybe it would make sense to only do this when creating the image and not have a hook which runs on every pacman invocation?

**Comment by bandresen** [comment]
Yeah that hook is really terrible if you want to actually use this package for that purpose.

**Comment by pierres** [comment]
I'll keep the sync db at least.

**Comment by mikkeloscar** [comment]
@pierres Thanks!
