### ISSUE TITLE
Should I use library/archlinux instead of archlinux/base ?

### ISSUE THREAD

**Issue by ny-a** [archlinux/archlinux-docker#31]
overview of [archlinux/base](https://hub.docker.com/r/archlinux/base/) and non-latest tags are deleted now.

Is [library/archlinux](https://hub.docker.com/_/archlinux) your new preferable image?

**Comment by shibumi** [comment]
Hello @ny-a,
https://hub.docker.com/_/archlinux is the official image. Please do not use archlinux/base.

**Comment by ny-a** [comment]
@shibumi 
Thank you for replying. I understood.
This project's description (url) contains archlinux/base link. could you change it?

**Comment by shibumi** [comment]
@ny-a yes, we are going to change it.
