### ISSUE TITLE
/etc/os-release symlink isn't created automatically

### ISSUE THREAD

**Issue by swrobel** [archlinux/archlinux-docker#33]
I was under the impression that systemd automagically symlinks `/etc/os-release` to `../usr/lib/os-release` but this doesn't seem to be happening for some reason on the arch docker image. I discovered by trial & error w/ older versions of the image that reinstalling or upgrading `cryptsetup` will create the symlink ... why, I don't know.

```
$ docker run -it archlinux:20200407 sh -c "ls -l /etc/os-release; pacman -Sy --noconfirm cryptsetup > /dev/null; ls -l /etc/os-release"
ls: cannot access '/etc/os-release': No such file or directory
warning: cryptsetup-2.3.1-1 is up to date -- reinstalling
lrwxrwxrwx 1 root root 21 Apr 21 23:36 /etc/os-release -> ../usr/lib/os-release
```

**Comment by swrobel** [comment]
As a bit of context: the same issue doesn't present when using [archlinux/base](https://hub.docker.com/r/archlinux/base)

**Comment by shibumi** [comment]
Sorry for the late reply.
This is interesting. @SantiagoTorres maybe we should manually set a link to /usr/lib/os-release in the image?

**Comment by SantiagoTorres** [comment]
I just built 20200607. I'm still investigating why this doesn't happen automatically. I think it's systemd that's doing things, and the rootless build doesn't do this. For now I'll update the Dockerfile to do the symlink manually and try to come to a more idiomatic solution in the near future.

**Comment by SantiagoTorres** [comment]
Also, if anybody can confirm this takes care of the issue, I'll close it

**Comment by njam** [comment]
@SantiagoTorres lgtm
```
podman run --rm -it docker.io/library/archlinux:20200605 ls -l /etc/os-release
lrwxrwxrwx 1 root root 19 Jun  8 19:19 /etc/os-release -> /usr/lib/os-release
```

**Comment by swrobel** [comment]
Apologies for taking so long to test this fix. I can confirm my issue is resolved!

**Comment by shibumi** [comment]
@swrobel thanks for reporting it :)
