### ISSUE TITLE
locale

### ISSUE THREAD

**Issue by piec** [archlinux/archlinux-docker#4]
Hi,

The `/etc/locale.conf` exists and is set to `LANG=en_US.UTF-8` 
But a simple `docker run -it archlinux/base bash` doesn't have this locale set.

Should `/etc/profile.d/locale.sh` be sourced in an entrypoint of the image?

Cheers

```
docker run -it archlinux/base
[root@821fd2557ae3 /]# locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
[root@821fd2557ae3 /]# cat /etc/locale.conf 
LANG=en_US.UTF-8
[root@821fd2557ae3 /]#
```

**Comment by pierres** [comment]
Not sure actually. It is interesting though as none of the other official images (like Debian) have default locale set.
