### ISSUE TITLE
Current mirror is broken.

### ISSUE THREAD

**Issue by mikkeloscar** [archlinux/archlinux-docker#9]
I have a build based on this image which is failing because the mirror is timing out:

```
error: failed retrieving file 'community.db' from mirror.leaseweb.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
```

https://travis-ci.org/mikkeloscar/archlinux-docker/builds/452344255#L561

Can we update the mirror? I'm not sure which one to use instead otherwise I would have made a PR :)

**Comment by shibumi** [comment]
Hi,
Normally `pacman` should automatically change to another mirror. I am wondering why this is not happening here. @SantiagoTorres @pierres do you have an idea?

**Comment by barthalion** [comment]
And it does so, when there is anything to switch to. No need to wonder about it: https://github.com/archlinux/archlinux-docker/blob/master/rootfs/etc/pacman.d/mirrorlist

**Comment by shibumi** [comment]
Ahh why the hell do we have such a small mirrorlist?

**Comment by SantiagoTorres** [comment]
I'm perfectly fine with doing so. I really see no reason to cut bytes on a comparatively small file.

**Comment by pierres** [comment]
I added rackspace as they also provide various servers depending on the users location. It would be best if we had a service that would redirect to the nearest mirror. Till then users should configure their favorite mirror. The defaults are just for convenience.

**Comment by shibumi** [comment]
redirecting to a nearest mirror is difficult to achieve. We would need a big cdn like cloudflare. But why don't you just add the whole mirror list? We are talking about a few kilobytes here.
